version: '3'
services:
  simple-sms-notify-service-dev:
    container_name: simple-sms-notify-service-dev
    image: odjhey/simple-sms-notify-service:latest
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    command: 'node index.js'
    ports:
      - '9090:8080'
    environment:
      PORT: '8080'
